spring:
  datasource:
    url: jdbc:h2:~/data/data
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  tomcat:
    basedir: ./log/local
